openapi: 3.0.0
info:
  title: Exo1
  version: 1.0.0
servers:
  - url: 'http://127.0.0.1:8000'
paths:
  /ping:
    get:
      summary: Retourne 'pong'
      responses:
        '200':
          description: Succès
          content:
            text/plain:
              example: "pong"

