openapi: 3.0.0
info:
  title: API de gestion d'utilisateurs
  version: 1.0.0
paths:
  /users:
    get:
      summary: Récupère une liste d'utilisateurs
      parameters:
        - name: page
          in: query
          required: false
          schema:
            type: integer
            minimum: 1
          description: Numéro de la page à récupérer
        - name: size
          in: query
          required: false
          schema:
            type: integer
            minimum: 1
          description: Nombre d'utilisateurs par page
      responses:
        '200':
          description: Liste des utilisateurs retrouvés
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 1
                    name:
                      type: string
                      example: Alice
                    email:
                      type: string
                      format: email
                      example: alice@example.com
        '400':
          description: Mauvais types de paramètres fournis
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Bad types for provided query parameters
